### ISSUE TITLE
Exception from: run Usecols do not match columns, columns expected but not found: ['TITLE', 'SKU', 'UPC', 'BRAND']

### ISSUE THREAD

**Issue by ghost** [bhuiyanmobasshir94/google-shopping-scraper#1]
Created and uploaded a csv with exactly columns below
BRAND | SKU | UPC | TITLE
but getting error "Exception from: run Usecols do not match columns, columns expected but not found: ['TITLE', 'SKU', 'UPC', 'BRAND']"
Any idea?

**Comment by bhuiyanmobasshir94** [comment]
@mehran-01 I am very much sorry to reply to you very late, this is self explanatory, column names are expected in exact format and order -> ['TITLE', 'SKU', 'UPC', 'BRAND']. That means you should put Title in the first column then SKU and so are the others.
